// <auto-generated />
using Codex.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Codex.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030022922_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Codex.Models.Computers", b =>
                {
                    b.Property<int>("IdComputers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdComputers"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdComputers");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("Codex.Models.Favorites", b =>
                {
                    b.Property<int>("IdFavorites")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFavorites"));

                    b.Property<int>("IdComputers")
                        .HasColumnType("int");

                    b.HasKey("IdFavorites");

                    b.HasIndex("IdComputers");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Codex.Models.TypeUser", b =>
                {
                    b.Property<int>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdType"));

                    b.Property<string>("Type_User")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdType");

                    b.ToTable("TypeUser");
                });

            modelBuilder.Entity("Codex.Models.Users", b =>
                {
                    b.Property<int>("IdUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsers"));

                    b.Property<int?>("IdFavorites")
                        .HasColumnType("int");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsers");

                    b.HasIndex("IdFavorites");

                    b.HasIndex("IdType");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Codex.Models.Favorites", b =>
                {
                    b.HasOne("Codex.Models.Computers", "Computers")
                        .WithMany()
                        .HasForeignKey("IdComputers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computers");
                });

            modelBuilder.Entity("Codex.Models.Users", b =>
                {
                    b.HasOne("Codex.Models.Favorites", "Favorites")
                        .WithMany()
                        .HasForeignKey("IdFavorites");

                    b.HasOne("Codex.Models.TypeUser", "TypeUser")
                        .WithMany()
                        .HasForeignKey("IdType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorites");

                    b.Navigation("TypeUser");
                });
#pragma warning restore 612, 618
        }
    }
}
